connection.dialect = org.hibernate.dialect.PostgreSQLDialect
connection.driver_class = org.postgresql.Driver
connection.url = jdbc:postgresql://dhis2-db/dhis
connection.username = dhis
connection.password = dhis

system.audit.enabled = off

# The CAPS route targets the plain-HTTP api container.
route.remote_servers_allowed = http://*
